package racingcar;

public enum GameStatus {
    READY_TO_INPUT_CARNAMES,
    READY_TO_INPUT_ROUNDNUMBER,
    START_PROCEED_EACH_ROUND,
    COMPLETE_TOTAL_ROUND,
    COMPLETE_SELECT_WINNER,
    END_OF_RACING_GAME
}
